---
- name: Install Packer
  hosts: 127.0.0.1
  connection: local
  become: true

  tasks:
  - name: Add Hashicorp apt key
    ansible.builtin.apt_key:
      url: https://apt.releases.hashicorp.com/gpg
      state: present

  - name: Add the official HashiCorp Linux repository
    apt_repository:
      repo: "deb [arch=amd64] https://apt.releases.hashicorp.com {{ ansible_distribution_release | lower }} main"
      state: present

#  - name: Update the `apt` package index
#    apt:
#      update_cache: yes

  - name: Install HashiCorp Packer
    package:
      name: packer
      state: present

  - name: Gather the package facts
    ansible.builtin.package_facts:
      manager: auto

  - name: Check whether Packer is installed
    ansible.builtin.debug:
      msg: "{{ ansible_facts.packages['packer'] }}"
    when: "'packer' in ansible_facts.packages"
