
variable "client_id" {
   default =   env("ARM_CLIENT_ID")
}
variable "subscription_id" {
   default =   env("ARM_SUBSCRIPTION_ID")
}
variable "client_secret" {
   default =   env("ARM_CLIENT_SECRET")
}
variable "tenant_id" {
   default =   env("ARM_TENANT_ID")
}
variable "location" {
    type = string
    default = "East US"
}
variable "managed_image_name" {
    type = string
    default = "RedHat-8.4"
}
variable "managed_image_resource_group_name" {
    type = string
    default = "DeployRgroup"
}
variable "vm_size" {
    type = string
    default = "Standard_DS2_v2"
}
variable "build_username" {
    type = string
    default = "defaultuser"
}

variable "build_password" {
    type = string
    default = "1234defaultpass"
}

variable "communicator_port" {
    type = number
    default = 22
}

source "azure-arm" "autogenerated_1" {

  client_id                         = var.client_id
  client_secret                     = var.client_secret
  subscription_id                   = var.subscription_id
  tenant_id                         = var.tenant_id
  image_offer                       = "RHEL"
  image_publisher                   = "RedHat"
  image_sku                         = "84-gen2"
  location                          = var.location
  managed_image_name                = var.managed_image_name
  managed_image_resource_group_name = var.managed_image_resource_group_name
  os_type                           = "Linux"
  vm_size                           = var.vm_size

  // Communicator
  communicator       = "ssh"
  ssh_username       = var.build_username
  ssh_password       = var.build_password
  ssh_port           = var.communicator_port

}

build {
  sources = ["source.azure-arm.autogenerated_1"]
  
  provisioner "shell" {
    script  = "./packer/azure/red_hat/Scripts/rhel8_CIS_V2.0.0.sh"
  }
  #provisioner "shell" {
    #script  = "./packer/azure/red_hat/Scripts/test.sh"
  #}
  provisioner "shell"{
    execute_command = "chmod +x {{ .Path }}; {{ .Vars }} sudo -E sh '{{ .Path }}'"

    inline  = [
      "sudo /usr/sbin/waagent -force -deprovision+user && export HISTSIZE=0 && sudo sync"
    ]

    inline_shebang = "/bin/sh -x"
  }
}
